### ISSUE TITLE
Not work on Android 7.1.2

### ISSUE THREAD

**Issue by nicodiaz101** [arovlad/bromite-webview-overlay#18]
I have a Samsung Galaxy Tab A6 (2016) SM-T280 with Lineage OS 14.1 installed. When i tried to install with TWRP fail with error 1.
With the magisk module it flash correctly but after reboot, the system enter in bootloop.
Some advice, alternative or solution?
PD: The ROM was abandoned but it´s the only ROM for this device.

**Comment by Alliegaytor** [comment]
I had the same issue @nicodiaz101. I followed the manual installation guide detailed [here](https://github.com/arovlad/bromite-webview-overlay#manual-installation), but that also didn't work for me. In my issue (#20) I show how I got it working. Hope it works for you as well.

**Comment by nicodiaz101** [comment]
Thanks! I found another solution using the experimental build of AnyWebview Xposed Module and it works great with Mulch Webview
